In [1]:
%load_ext autoreload
%autoreload 2

In [11]:
import meerkat as mk

import numpy as np
dp =mk.DataPanel(
    {"a": np.arange(10),
     "b": np.arange(10) + 1,
     "c": np.arange(10) + 2
    }
)

In [ ]:
dp

In [2]:
import domino
import numpy as np
from sklearn.datasets import make_blobs


In [3]:
from domino._slice.mixture._generalized import GeneralizedMixture, GaussianVariable, CategoricalVariable

In [4]:
mm = GeneralizedMixture(
    n_components=5,
    variables=[
        GaussianVariable(name="x"),
        CategoricalVariable(name="y"),
    ]
)

In [5]:
length = 128
gaussian_means = np.array(
    [
        [0.0, 5.0, 0.0, 0.0, 0.0],
        [1.0, 1.0, 4.0, 0.0, 0.0],
        [1.0, 0.0, 0.0, 5.0, 1.0],
        [5.0, 2.0, 0.0, 1.0, 10.0],
        [1.0, 10.0, 2.0, 2.0, 0.0],
    ]
)

emb, clusters = make_blobs(
    n_samples=length, centers=gaussian_means, cluster_std=1.0, random_state=42
)

targets = clusters == 1
preds = (clusters == 1) | (clusters == 2)

In [40]:
mm = GeneralizedMixture(
    n_components=2,
    variables=[
        GaussianVariable(name="x"),
        CategoricalVariable(name="y", weight=0),
    ]
)

mm.fit(
    x=emb,
    y=targets
)
out = mm.predict(x=emb)
out

  1%|          | 1/100 [00:00<00:00, 269.12it/s]


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1])

In [41]:
((clusters == 1).astype(int) != out)

array([False,  True,  True,  True,  True,  True, False,  True, False,
        True, False, False, False,  True,  True, False, False,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True, False, False,  True,  True,
        True, False,  True, False, False,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
       False,  True,  True, False,  True,  True,  True, False, False,
       False,  True, False, False,  True,  True, False,  True,  True,
       False, False,  True, False, False,  True, False,  True,  True,
       False,  True,  True,  True, False,  True,  True, False, False,
        True,  True, False, False,  True,  True, False, False,  True,
        True,  True,  True, False, False, False, False,  True, False,
        True,  True,  True,  True, False,  True,  True, False,  True,
       False, False]

In [26]:
clusters

array([3, 0, 0, 0, 0, 2, 1, 4, 1, 4, 3, 1, 1, 0, 0, 3, 1, 4, 3, 4, 4, 4,
       4, 2, 1, 2, 2, 0, 4, 0, 3, 4, 3, 1, 0, 2, 4, 1, 4, 3, 3, 2, 1, 1,
       2, 2, 4, 2, 2, 2, 2, 0, 1, 2, 4, 2, 0, 4, 4, 1, 2, 3, 0, 3, 0, 2,
       3, 0, 2, 0, 3, 3, 1, 2, 1, 3, 0, 0, 1, 0, 4, 1, 3, 4, 1, 1, 2, 3,
       2, 4, 3, 0, 0, 4, 3, 2, 4, 3, 3, 0, 4, 3, 3, 4, 4, 3, 1, 0, 0, 4,
       2, 1, 1, 1, 3, 2, 1, 2, 0, 0, 2, 1, 4, 2, 1, 0, 3, 1])